locale: 'en'
logo_url: https://saferjourno.org/images/cms-logo.svg

site_url: https://saferjourno.org
display_url: https://saferjourno.org

backend:
  name: git-gateway
  repo: uradotdesign/saferjourno
  branch: main

local_backend: true

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, de]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: introduction
    label: Introduction page
    identifier_field: title
    description: Here we can edit the introduction page content.
    i18n: true
    extension: md
    folder: content/introduction
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true
  - name: chapters
    label: Chapters
    identifier_field: title
    description: Here we can edit individual Chapters page content.
    i18n: true
    extension: md
    folder: content/chapters
    create: true
    delete: true
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true
  - name: scenarios
    label: Scenarios
    identifier_field: title
    description: Here we can edit the scenarios page content.
    i18n: true
    extension: md
    folder: content/scenarios
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true
  - name: advanced-guides
    label: Advanced Guides
    identifier_field: title
    description: Here we can edit the advanced guides page content.
    i18n: true
    extension: md
    folder: content/advanced-guides
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true
  - name: digital-risk-assessment-template
    label: Digital Risk Assessment
    identifier_field: title
    description: Here we can edit the digital risk assessment template content.
    i18n: true
    extension: md
    folder: content/digital-risk-assessment-template
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true