locale: 'en'
logo_url: https://saferjourno.org/images/cms-logo.svg

site_url: https://saferjourno.org
display_url: https://saferjourno.org

backend:
  name: git-gateway
  repo: internews/saferjourno
  branch: main

local_backend: true

publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, de]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: introduction
    label: Introduction page
    identifier_field: title
    description: Here we can edit the introduction page content.
    i18n: true
    extension: md
    folder: content/introduction
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true
  - name: chapter-1
    label: Chapter 1
    identifier_field: title
    description: Here we can edit the Chapter 1 page content.
    i18n: true
    extension: md
    folder: content/chapter-1
    create: false
    delete: false
    fields:
      - label: Content
        name: body
        widget: markdown
        i18n: true